In [1]:
import pandas as pd
import numpy as np

In [73]:
data = pd.read_csv("data/records.csv")

In [84]:
data["CIK"]

0         77098
1        785161
2         31791
3         30819
4         30697
         ...
9594     916540
9595    1341766
9596    1102432
9597     936468
9598    1600626
Name: CIK, Length: 9599, dtype: int64

In [85]:
CIK_CUSIP = pd.read_csv("data/cik-cusip_mapping_1993-2018.csv")
CIK_CUSIP.index = pd.MultiIndex.from_frame(CIK_CUSIP[["cik", "fyear"]])
CIK_CUSIP["cik"]

cik      fyear
20       1993          20
         1994          20
         1995          20
         1996          20
         1997          20
                   ...
1739520  2015     1739520
         2016     1739520
         2017     1739520
         2018     1739520
         2019     1739520
Name: cik, Length: 2042091, dtype: int64

In [87]:
len(set(data["CIK"]).difference(set(data["CIK"]).intersection(CIK_CUSIP["cik"])))

1312

In [54]:
print(65771 in CIK_CUSIP["cik"])
d = CIK_CUSIP[["cusip"]].to_dict()

True

In [60]:
(65771, 1995) in d["cusip"]

True

In [82]:
data.columns
len(data)

9599

In [94]:
cik = [d["cusip"][x]  if x in d["cusip"] else np.nan for x in zip(data["CIK"], [int(x[:4]) for x in data["date"]])]

In [95]:
data["CUSIP"] = pd.Series(cik, index=data.index)

In [96]:
data

          CIK        date     CUSIP
0       77098  1995-03-03  02909210
1      785161  1995-02-01  42192410
2       31791  1995-02-09  26845710
3       30819  1995-03-30  12650110
4       30697  1995-01-18  89592710
...       ...         ...       ...
9594   916540  2018-11-06  23726610
9595  1341766  2018-11-08  15118V20
9596  1102432  2018-11-20  92679510
9597   936468  2018-10-23  53983010
9598  1600626  2018-12-20       NaN

[9599 rows x 3 columns]

In [88]:
data.to_csv("data/records.csv", index=False)

KeyboardInterrupt:

In [ ]:
data = pd.read_csv("data/sub_dsf.csv")

In [4]:
data.head()
data.replace('[a-Z]+',np.NaN,inplace=True)

In [5]:
data.to_pickle("data/sub_dsf.pkl")

In [2]:
data = pd.read_pickle("data/sub_dsf.pkl")

In [7]:
data.head()

      CUSIP        DATE      VOL       RET
0  12709510  01/14/1986      NaN       NaN
1  12709510  01/16/1986      NaN       NaN
2  12709510  01/17/1986   6000.0       NaN
3  12709510  01/20/1986  33700.0  0.029412
4  12709510  01/21/1986  20800.0  0.057143

In [8]:
ret_data = data.set_index(["CUSIP", "DATE"])['RET'].unstack(fill_value=0)

MemoryError: Unable to allocate array with shape (1, 17567450) and data type float64

In [4]:
ret_data.head()

DATE,01/02/1970,01/02/1973,01/02/1974,01/02/1975,01/02/1976,01/02/1979,01/02/1980,01/02/1981,01/02/1985,01/02/1986,...,12/31/2004,12/31/2007,12/31/2008,12/31/2009,12/31/2010,12/31/2012,12/31/2013,12/31/2014,12/31/2015,12/31/2018
CUSIP,,,,,,,,,,,,,,,,,,,,,
95710,-0.006897,0.000000,0.000000,0.125000,0.000000,0.000000,0.000000,0.000000,-0.010363,-0.015000,...,-0.003033,-0.017349,0.043836,-0.016190,-0.011278,0.018897,-0.007636,-0.011046,-0.020977,0.032808
105510,0,0,0.000000,0.153846,0.000000,-0.075949,-0.057471,0.066667,0.005376,0.013575,...,-0.004000,0.002240,0.005263,-0.013439,0.006062,0.016651,0.001649,-0.014359,-0.010245,0.013571
282410,-0.009804,0.008929,0.025063,-0.004926,-0.021212,-0.003704,-0.051672,0.006637,-0.026946,-0.005484,...,-0.005754,-0.018871,0.003950,-0.010084,0.007147,0.016765,-0.002083,-0.014664,-0.007952,0.017443
780010,0.013605,0.013699,0.000000,0.082353,0.000000,0.000000,-0.041176,0.026667,-0.014599,0.019892,...,0.000539,-0.007660,0.054441,-0.005682,-0.011472,0.017798,0.001668,-0.007054,-0.003817,0.015566
1165910,0.094118,0.000000,0.025641,0.142857,0.054054,0.051282,0.000000,-0.030303,-0.016529,0.000000,...,0.009039,-0.003189,0.015272,-0.015945,-0.013916,0.008425,0.018462,-0.000167,-0.011419,0.008954

In [5]:
ret_data = data[["CUSIP", "DATE", "RET"]].pivot(index="DATE", columns = "CUSIP", values="RET")

MemoryError: Unable to allocate array with shape (17567450,) and data type int64

In [5]:
ret_data.astype("float64", copy=False)
ret_data.index = pd.to_datetime(ret_data.index)

ValueError: could not convert string to float: 'B'

In [19]:
ret_data = ret_data.sort_index()

In [21]:
ret_data.head()

CUSIP,95710,105510,282410,780010,1165910,2942910,3439310,4273510,4333910,5377410,...,M8743P10,N4727910,N6865W10,P8744Y10,Q9235V10,V8726M10,Y0553W10,Y2573F10,Y7169G10,Y9530810
DATE,,,,,,,,,,,,,,,,,,,,,
1970-01-02,-0.006897,NaN,-0.009804,0.013605,0.094118,NaN,0.146341,0.013043,0.095238,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1970-01-05,-0.017361,NaN,0.003300,0.033557,0.021505,NaN,0.021277,-0.004292,0.054348,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1970-01-06,-0.010601,NaN,-0.006579,-0.012987,-0.010526,NaN,0.000000,-0.025862,-0.025773,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1970-01-07,-0.021429,NaN,-0.009934,-0.006579,-0.021277,NaN,0.000000,0.004425,-0.010582,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1970-01-08,0.010949,NaN,0.003344,0.000000,0.000000,NaN,0.041667,0.008811,0.080214,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
ret_data.astype("float64", copy=False).head()

ValueError: could not convert string to float: 'C'

In [86]:
ret_data.dtypes

CUSIP
95710       object
105510      object
282410      object
780010      object
1165910     object
             ...
V8726M10    object
Y0553W10    object
Y2573F10    object
Y7169G10    object
Y9530810    object
Length: 3764, dtype: object

In [3]:
ret_data = pd.read_pickle('data/ret_data.pkl')

In [8]:
ret_data.iloc[0]

CUSIP
95710       -0.006897
105510            NaN
282410      -0.009804
780010       0.013605
1165910      0.094118
              ...
V8726M10          NaN
Y0553W10          NaN
Y2573F10          NaN
Y7169G10          NaN
Y9530810          NaN
Name: 1970-01-02 00:00:00, Length: 3764, dtype: object

In [9]:
index_data = pd.read_sas("data/dsi.sas7bdat")
index_data.index = pd.to_datetime(index_data["date"])

In [10]:
index_data.head()

,date,VWRETD,VWRETX,EWRETD,EWRETX,TOTVAL,TOTCNT,USDVAL,USDCNT,SPRTRN,SPINDX
date,,,,,,,,,,,
1925-12-31,1925-12-31,NaN,NaN,NaN,NaN,27487487.2,503.0,NaN,NaN,NaN,NaN
1926-01-02,1926-01-02,0.005689,0.005689,0.009516,0.009516,27600296.6,497.0,27366755.7,494.0,NaN,NaN
1926-01-04,1926-01-04,0.000706,0.000706,0.005780,0.005780,27577892.1,502.0,27479721.6,495.0,NaN,NaN
1926-01-05,1926-01-05,-0.004821,-0.004867,-0.001927,-0.002030,27530212.5,501.0,27561757.1,499.0,NaN,NaN
1926-01-06,1926-01-06,-0.000423,-0.000427,0.001182,0.001155,27618772.6,505.0,27526837.5,500.0,NaN,NaN

In [12]:
records = pd.read_csv("data/records.csv")

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [33]:
from datetime import datetime, timedelta

In [34]:
date_format = "%m/%d/%Y"
a = datetime.strptime('8/18/2008', date_format)
b = datetime.strptime('9/26/2008', date_format)
a - timedelta(12)

datetime.datetime(2008, 8, 6, 0, 0)

In [47]:
index_data[a : b].iloc[-1]

date      2008-09-26 00:00:00
VWRETD            -0.00198477
VWRETX             -0.0022433
EWRETD            -0.00825126
EWRETX            -0.00858331
TOTVAL             1.6648e+10
TOTCNT                   6888
USDVAL            1.66857e+10
USDCNT                   6887
SPRTRN             0.00316744
SPINDX                1213.01
Name: 2008-09-26 00:00:00, dtype: object

In [43]:
np.linalg.lstsq(np.array([[1, 2, 3], [1, 1, 1]]).T, [2, 3, 5])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.

(array([1.5       , 0.33333333]),
 array([0.16666667]),
 2,
 array([4.07914333, 0.60049122]))

In [56]:
list(zip([1, 2], [3, 4]))

[(1, 3), (2, 4)]

In [22]:
def cal_car(date, cusip):
    date_format = "%Y-%m-%d"
    date = datetime.strptime(date, date_format)
    begin, end = date - timedelta(345),  date - timedelta(96)
    result = {0: np.nan, 1:np.nan, 3:np.nan, 5: np.nan}
    keys = ["car_w0", "car_w1", "car_w3", "car_w5"]
    if cusip in ret_data.columns:
        return {k: v for k, v in zip(keys, list(result.values()))}        

    ret = ret_data[cusip][begin: end].astype('float64')

    mkt = index_data.loc[begin: end, "VWRETX"]

    beta = ret.cov(mkt)
    alpha = ret.mean() - mkt.mean() * beta

    
    for w in result:
        try:
            wbegin, wend = date - timedelta(w), date + timedelta(w)
            result[w] = (ret_data.loc[wbegin: wend, cusip].astype('float64') - beta * index_data.loc[wbegin: wend, "VWRETX"] - alpha).sum()
        except:
            pass

    return {k: v for k, v in zip(keys, list(result.values()))}

In [23]:
cal_car("1995-02-01", 12650110)

{'car_w0': -0.0018264973575012452,
 'car_w1': 0.024093469907702884,
 'car_w3': 0.024365442224538007,
 'car_w5': -0.03897160000790016}

In [13]:
pd.DataFrame([{"a":1, "b":2},{"a":2, "b":3}])

   a  b
0  1  2
1  2  3

In [12]:

for _ ,row in records.head().iterrows():
    print(row)

CIK           77098
date     1995-03-03
CUSIP      02909210
Name: 0, dtype: object
CIK          785161
date     1995-02-01
CUSIP      42192410
Name: 1, dtype: object
CIK           31791
date     1995-02-09
CUSIP      26845710
Name: 2, dtype: object
CIK           30819
date     1995-03-30
CUSIP      12650110
Name: 3, dtype: object
CIK           30697
date     1995-01-18
CUSIP      89592710
Name: 4, dtype: object