In [1]:
import sys
sys.path.append("./lib64/python3.6/site-packages")

In [39]:
import pandas as pd
import numpy as np
import os
import re

In [5]:
dct = pd.read_csv('data/LoughranMcDonald_MasterDictionary_2018.csv')

In [8]:
dct.columns

Index(['Word', 'Sequence Number', 'Word Count', 'Word Proportion',
       'Average Proportion', 'Std Dev', 'Doc Count', 'Negative', 'Positive',
       'Uncertainty', 'Litigious', 'Constraining', 'Superfluous',
       'Interesting', 'Modal', 'Irr_Verb', 'Harvard_IV', 'Syllables',
       'Source'],
      dtype='object')

In [10]:
dct['Negative'].unique()

array([   0, 2009, 2011, 2014, 2012])

In [11]:
dct['Positive'].unique()

array([   0, 2009, 2012, 2011])

In [15]:
negative = dct.loc[dct['Negative'] > 0 ,'Word']
positive = dct.loc[dct['Positive'] > 0 ,'Word']

In [26]:
positive = set(s.lower() for s in positive)
negative = set(s.lower() for s in negative)

In [37]:
"a|b.c".split()

['a|b.c']

In [137]:
prog_txt = re.compile('<TEXT>([.\\\\]*)</TEXT>')
prog_wd = re.compile('[a-zA-Z]+')

In [138]:
prog_txt.findall(test)

[]

In [143]:
prog_line = re.compile('\n')
prog_nbsp = re.compile('&nbsp;')
prog_tag = re.compile('<.*?>')

In [66]:
prog_wd.findall("A is Ok")

['A', 'is', 'Ok']

In [152]:
res = []
for root, _, files in os.walk("data/"):
    for file in files:
        CIK, date = file.split('|')[0], file.split('|')[1].split('.')[0]
        d = {'CIK': int(CIK), 'date': date}
        with open(root + '/' + file, 'r') as file:
            text = file.read()
            text = text[text.find('<DOCUMENT>'): text.find('</DOCUMENT>')]

            text = prog_line.sub(' ', text)
            text = prog_nbsp.sub(' ', text)
            text = prog_tag.sub('', text)
            
            words = prog_wd.findall(text)
            words = [w.lower() for w in words]
            
            diff = 0
            for w in words:
                if w in positive:
                    diff += 1
                elif w in negative:
                    diff -= 1
            
            try:
                d['pos_neg'] = diff / len(words)
            except:
                d['pos_neg'] = np.nan
            res.append(d)
            
res_df = pd.DataFrame(res)

In [154]:
res_df[res_df['pos_neg'] > 0]

          CIK        date   pos_neg
0     1405041  2012-12-05  0.002083
1     1025536  2012-11-30  0.002770
2     1415684  2012-11-28  0.003736
3     1512931  2012-11-13  0.002299
4     1005276  2012-10-02  0.010622
...       ...         ...       ...
9544   896429  2011-06-01  0.005535
9546  1322439  2011-04-29  0.004329
9547  1000180  2011-04-21  0.003802
9548  1345840  2011-05-05  0.002890
9550   866970  2011-04-28  0.000985

[3646 rows x 3 columns]