In [1]:
import sys
sys.path.append("./lib64/python3.6/site-packages")

In [3]:
import pandas as pd
import numpy as np
import os
import re

from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk import tokenize

In [50]:
import nltk
# nltk.download('punkt')
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

True

In [65]:
res = []
sid = SentimentIntensityAnalyzer()
for root, _, files in os.walk("data/"):
    for file in files:
        CIK, date = file.split('|')[0], file.split('|')[1].split('.')[0]
        entry = {'CIK': int(CIK), 'date': date}
        with open(root + '/' + file, 'r') as f:
            text = f.read()
            text = text[text.find('<DOCUMENT>'): text.find('</DOCUMENT>')]
            text = prog_line.sub(' ', text)
            text = prog_nbsp.sub(' ', text)
            text = prog_tag.sub('', text)

            sentences = tokenize.sent_tokenize(text)
            scores = [sid.polarity_scores(stn)['compound'] for stn in sentences]
            try:
                entry['tone'] = sum(scores) / len(scores)
            except:
                entry['tone'] = np.nan
        res.append(entry)

res_df = pd.DataFrame(res)

In [66]:
res_df[res_df['tone'] > 0]

          CIK        date      tone
0     1405041  2012-12-05  0.420645
1     1025536  2012-11-30  0.140167
2     1415684  2012-11-28  0.256700
3     1512931  2012-11-13  0.339691
4     1005276  2012-10-02  0.233467
...       ...         ...       ...
9548  1000180  2011-04-21  0.352957
9549  1345840  2011-05-05  0.187763
9550  1312073  2011-05-19  0.336457
9551   866970  2011-04-28  0.442136
9552   902791  2011-05-20  0.416400

[8790 rows x 3 columns]

In [64]:
res_df['tone'] = res_df['tone'].apply(lambda x: (x - x.min())/(x.max() - x.min()))

          CIK        date      tone
0     1405041  2012-12-05  0.333162
1     1025536  2012-11-30  0.205950
2     1415684  2012-11-28  0.268428
3     1512931  2012-11-13  0.349477
4     1005276  2012-10-02  0.262853
...       ...         ...       ...
9548  1000180  2011-04-21  0.283100
9549  1345840  2011-05-05  0.157930
9550  1312073  2011-05-19  0.346825
9551   866970  2011-04-28  0.420348
9552   902791  2011-05-20  0.362720

[9297 rows x 3 columns]

In [40]:
prog_line = re.compile('\n')
prog_nbsp = re.compile('&nbsp;')
prog_tag = re.compile('<.*?>')

In [29]:
test = "<abc>de<>"
prog.sub('', test)

'de'

In [56]:
sid = SentimentIntensityAnalyzer()

with open('data/2012/QTR4/1405041|2012-12-05.txt', 'r') as file:
    text = file.read()
    text = text[text.find('<DOCUMENT>'): text.find('</DOCUMENT>')]
    text = prog_line.sub(' ', text)
    text = prog_nbsp.sub(' ', text)
    text = prog_tag.sub('', text)
    
    sentences = tokenize.sent_tokenize(text)
    for sentence in sentences[1:]:
        ss = sid.polarity_scores(sentence)
        
        for k in sorted(ss):
            print('{0}: {1}, '.format(k, ss[k]), end='')

22 Corporate Woods Blvd.
compound: 0.0, neg: 0.0, neu: 1.0, pos: 0.0,

Albany, NY 12211  (address of principal executive offices) (Zip Code)  (Registrant&#146;s telephone number, including area code) (518) 533-4600  Not Applicable  (Former name or former address, if changed since last report)      Check the appropriate box below if the Form 8-K filing is intended to simultaneously satisfy the filing obligation of the registrant under any of the following provisions:      &#168; Written communications pursuant to Rule 425 under the Securities Act (17 CFR 230.425)      &#168; Soliciting material pursuant to Rule 14a-12 under the Exchange Act (17 CFR 240.14a-12)      &#168; Pre-commencement communications pursuant to Rule 14d-2(b) under the Exchange Act (17 CFR 240.14d-2(b))      &#168; Pre-commencement communications pursuant to Rule 13e-4(c) under the Exchange Act (17 CFR 240.13e-4(c))             Item 1.01 Entry into a Material Definitive Agreement.
compound: 0.8271, neg: 0.0, neu: 0.923, pos: 0.077,

Amendment to Senior Secured Credit Facility  On November 30, 2012, Momentive Performance Materials Inc. (the &#147;Company&#148;) entered into an incremental amendment to its senior secured credit agreement whereby certain revolving facility lenders agreed to make approximately $300.0 million of revolving facility commitments available for revolving facility loans under the Company&#146;s senior secured credit agreement.
compound: 0.975, neg: 0.0, neu: 0.606, pos: 0.394,

The incremental amendment and the new revolving commitments became effective on November 30, 2012 following the termination of the existing revolving commitments.
compound: 0.6249, neg: 0.0, neu: 0.757, pos: 0.243,

The new revolving commitments will mature on December 3, 2014.
compound: 0.5106, neg: 0.0, neu: 0.65, pos: 0.35,

The new revolving loans will bear interest at a rate per annum of LIBOR plus 4.75% until the date that is 60 days after November 16, 2012 from which time the new revolving loans will bear interest at a rate per annum of LIBOR plus 6.00%.
compound: 0.7184, neg: 0.0, neu: 0.875, pos: 0.125,

Item 2.03 Creation of a Direct Financial Obligation.
compound: 0.2732, neg: 0.0, neu: 0.741, pos: 0.259,

The information set forth under Item 1.01 above is incorporated by reference into this Item 2.03.
compound: 0.0, neg: 0.0, neu: 1.0, pos: 0.0,

Item 9.01 Financial Statements and Exhibits.
compound: 0.0, neg: 0.0, neu: 1.0, pos: 0.0,

(d) Exhibits              Exhibit 10.1    Second Incremental Facility Amendment, dated as of November 30, 2012, by and among Momentive Performance Materials Holdings Inc., Momentive Performance Materials Inc., Momentive Performance Materials USA Inc. and Momentive Performance Materials GmbH, the lenders party thereto and JPMorgan Chase Bank, N.A., as administrative agent.
compound: 0.4019, neg: 0.0, neu: 0.946, pos: 0.054,

2        SIGNATURES  Pursuant to the requirements of the Securities Exchange Act of 1934, as amended, the Company has duly caused this report to be signed on its behalf by the undersigned hereunto duly authorized.
compound: 0.296, neg: 0.0, neu: 0.936, pos: 0.064,

MOMENTIVE PERFORMANCE MATERIALS INC.
compound: 0.0, neg: 0.0, neu: 1.0, pos: 0.0,

Date: December 5, 2012      By:    /s/ William H. Carter           William H. Carter           Executive Vice President and Chief Financial Officer       EXHIBIT INDEX             Exhibit No.
compound: -0.296, neg: 0.091, neu: 0.909, pos: 0.0,

Description       10.1    Second Incremental Facility Amendment, dated as of November 30, 2012, by and among Momentive Performance Materials Holdings Inc., Momentive Performance Materials Inc., Momentive Performance Materials USA Inc. and Momentive Performance Materials GmbH, the lenders party thereto and JPMorgan Chase Bank, N.A., as administrative agent.
compound: 0.4019, neg: 0.0, neu: 0.943, pos: 0.057,